<?php
  $pagetitle = "Jakub Kulík";
  include('parts/header.phtml');
?>

<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Jakub Kulík</h1>
      <hr>

      <p>I am Computer science student at <a href="https://www.fit.cvut.cz/en/" target="_blank">Faculty of Information Technology</a> - <a href="https://www.cvut.cz/en/" target="_blank">Czech technical university in Prague</a> and Scout Leader at <a href="http://athabaska.org" target="_blank">Athabaska</a> group.</p>

      <p>You can find BI-PA2 course assignments <a href="md/tutorials">here</a>.</p>

      <p>Find me on <a href="https://facebook.com/jakub.kulik.522" target="_blank">Facebook</a>.</p>

      <p>My Github repository: <a href="https://github.com/kulikjak" target="_blank">here</a></p>

      <p>Contact me via email <a href="mailto:me@jakubkulik.cz" target="_blank">me@jakubkulik.cz</a> or <a href="mailto:kulikjak@fit.cvut.cz" target="_blank">kulikjak@fit.cvut.cz</a> (for university stuff).

    </div>
  </div>
</div>

<?php 
  include('parts/footer.phtml'); 
