<?php 

function parse_file($file_path) {
    $values = [];
    $file = file_get_contents($file_path);

    $beginning = strpos($file, "<!--") + 4;
    $ending = strpos($file, "-->");

    $content = trim(substr($file, $beginning, $ending - $beginning));
    $variables = explode("\n", $content);

    foreach ($variables as $key => $value) {
        preg_match('/\[([\w]+)\]: (.+)/', $value, $matches);
        if (count($matches) != 3)
            continue;
        $values[strtolower($matches[1])] = $matches[2];
    }

    $Parsedown = new Parsedown();
    $Parsedown->setBreaksEnabled(true);
    $Parsedown->setMarkupEscaped(false);
    $Parsedown->setUrlsLinked(true);

    $result = $Parsedown->text($file);

    // Add target to outside links to open them in new tab.
    $values['__result'] = preg_replace("/(<a\\b[^<>]*href=['\"]?http[^<>]+)>/is", "$1 target=\"_blank\">", $result);

    return $values;
}

if (!isset($lang)) $lang = "en";

$message = "";
$oplang = ($lang == "en") ? "cs" : "en";
$oplang_message = ($lang == "en") ?
    "This page is only available in czech language." :
    "Tato stránka je dostupná pouze v angličtině";

// Get correct file with lang extension.
if (file_exists("../markdown/{$file}.{$lang}.md")) {
    $values = parse_file("../markdown/{$file}.{$lang}.md");
}

// Get correct file without lang extension.
elseif (file_exists("../markdown/{$file}.md")) {
    $values = parse_file("../markdown/{$file}.md");
}

// Get file with lang extension of other language.
elseif (file_exists("../markdown/{$file}.{$oplang}.md")) {
    $values = parse_file("../markdown/{$file}.{$oplang}.md");
    $message = $oplang_message;
}

// Get index page with lang extension.
elseif (substr($file, -1) == '/' && file_exists("../markdown/{$file}index.{$lang}.md")) {
    $values = parse_file("../markdown/{$file}index.{$lang}.md");
}

// Get index page without lang extension.
elseif (substr($file, -1) == '/' && file_exists("../markdown/{$file}index.md")) {
    $values = parse_file("../markdown/{$file}index.md");
}

// Get index page with lang extension of other language.
elseif (substr($file, -1) == '/' && file_exists("../markdown/{$file}index.{$oplang}.md")) {
    $values = parse_file("../markdown/{$file}index.{$oplang}.md");
    $message = $oplang_message;
}

// Sadly we don't have this page in any language
else {
    $values = parse_file("../markdown/404.md");
}

?>

<html lang="<?= $lang ?>">
<head>
    <meta charset="utf-8">

    <title><?= $values['title'] ?></title>
    <link rel="shortcut icon" type="image/png" href="/favicon.png">

    <meta name="author" content="Jakub Kulík">
    <link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <link rel="stylesheet" type="text/css" href="/static/css/markdown.css">

<?php if (isset($values["cssfile"])): ?>
    <link rel="stylesheet" type="text/css" href="/static/css/<?= $values['cssfile'] ?>">
<?php endif; ?>

<?php if (isset($values["css"])): ?>
    <style type="text/css">
        <?= $values['css'] ?>
    </style>
<?php endif; ?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta name="google-site-verification" content="8o97nwQbFj_s0dDTGdONeYByTUsw4rRYytfCXMrTUBo" />

    <link rel="stylesheet" href="/static/highlight/styles/googlecode.css">
</head>
<body id="preview">

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <?= $values['__result'] ?>
        </div>
    </div>
</div>

<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-92628862-1', 'auto');
    ga('send', 'pageview');
</script>

<script type="text/javascript" src="/static/jquery-3.1.1.min.js"></script>
<script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/static/highlight/highlight.pack.js"></script>
<script type="text/javascript">
    hljs.initHighlightingOnLoad();
</script>

</body>
</html>
