<html lang="en-GB">
<head>
  <meta charset="utf-8">

  <title><?= $pagetitle ?></title>
  <?php /* <link rel="shortcut icon" type="image/png" href="/favicon.png"> */ ?>
  
  <meta name="author" content="Jakub Kulík">
  <link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="/css/main.css">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <meta name="google-site-verification" content="8o97nwQbFj_s0dDTGdONeYByTUsw4rRYytfCXMrTUBo" />
  <style type="text/css">
    
  </style>
</head>
<body>